### ISSUE TITLE
suggestion: automatic polar alignment

### ISSUE THREAD

**Issue by Trigger-broom-289** [polvinc/HEMY#10]
Hello,

Have you thought about integrating an automatic polar alignment, something like 
https://www.printables.com/model/784937-am3-electronic-polar-alignment?lang=en

Regards

**Comment by polvinc** [comment]
Wow, impressive design. I'm definitely going to look into integrating it into the HEMY base (in aluminium of course!). Thanks for the suggestion.

**Comment by polvinc** [comment]
You've made my brain hot! I think it will be for a HEMY v2.0, which could come out at the end of 2025. Thanks again for the suggestion.
