### ISSUE TITLE
[TechDraw] Missing dimensions on the tech drawings

### ISSUE THREAD

**Issue by Gophen** [polvinc/HEMY#2]
Hi,
This issue could be used to report any missing dimension(s) from the technical drawings.

Example :
- Part : T-Plate
- Feature : bottom 2 mounting holes
- Dimension : Height from the bottom of the part 
- Dimension in the plan : None, expected 10 mm like at the top
- Correction : Add dimensions as follows (or just give the height of the rectangle) :

![Copie d'écran_20241016_195709](https://github.com/user-attachments/assets/53054225-4c4d-46e8-b963-63ed3160ebcf)

What do you think ?

**Comment by polvinc** [comment]
It's a great idea, thx! It'll help me with my proofreading, and above all it'll get me motivated to make the corrections!
