### ISSUE TITLE
Progress and some emerging issues

### ISSUE THREAD

**Issue by martin0359** [polvinc/HEMY#3]
Dear Polvinc
I apologize for the three week delay, most of the parts were in place three weeks ago, but it wasn't until today that I finished  the assembly basicly.
I still have a few minor questions, starting with the simplest one.
1.Pin definition of motor including brakes (with rj45's, in the end I still used the rj45)
2.The part in the photo I couldn't get the screws on, the holes for the square CNC part underneath that is used to hold it in place don't seem to be quite accurate and I forgot to tap thread to this hole, it's held against another large head screw that seems to be tightened up and doesn't seem to interfere with the operation of the system. The other reason I didn't put the screws in was the belts were already over tensioned and I was worried about breaking them. Do you have any suggestions for this part of the tuning and assembly?
3.If possible, please check the other assembly details for me and ask questions, I hope this won't waste too much of your time!
4.Regarding those brakes, what are my options for testing and controlling them at this stage?

Finally, thank you and your partners for your great creations and unstinting sharing, bringing intellectual enjoyment to us across the ocean.
![IMG_4766](https://github.com/user-attachments/assets/2a663a13-667c-456c-a2c3-4ea1993808c6)
![IMG_4767](https://github.com/user-attachments/assets/9c1432f5-2583-483b-b325-e469d821531d)
![IMG_4768](https://github.com/user-attachments/assets/9941f84b-1a61-4fca-87e9-3dfb531306e9)
![IMG_4769](https://github.com/user-attachments/assets/e5996fe4-720b-4f41-8cd6-b9c5c3392190)
![IMG_4771](https://github.com/user-attachments/assets/19ff8ddb-e334-45a1-9168-03f9d51e5e8c)

**Comment by martin0359** [comment]
About the assembly location of the washers, could you please label in detail, I'm only using three thin washers right now and it seems to complete. I'm not sure what problems this could cause.

**Comment by polvinc** [comment]
Wow, that's a great achievement, I'm glad you went all the way with it.

> 1.Pin definition of motor including brakes (with rj45's, in the end I still used the rj45)

For the RJ45s, you need to refer to the electronics you are going to use (in my case, OnStep minipcb2). The HEMY electronics (with brake management) will have WIFI, USB C, and DC 12-25V jack input. A new plate will have to be machined to remove the new connectors.

>2.The part in the photo I couldn't get the screws on, the holes for the square CNC part underneath that is used to hold it in place don't seem to be quite accurate and I forgot to tap thread to this hole, it's held against another large head screw that seems to be tightened up and doesn't seem to interfere with the operation of the system. The other reason I didn't put the screws in was the belts were already over tensioned and I was worried about breaking them. Do you have any suggestions for this part of the tuning and assembly?

What length belt did you use? On the HEMYs I've built, I've never had any problems tensioning the belts or fitting this screw. On the DEC, however, there isn't much margin to insert the screw, so the groove would have to be enlarged. Suggestions I can make:
1. tap the M3 hole
2. enlarge the hole to diameter 4, and insert an M3 nut underneath.
3. In itself, two anchor points for the motors might be enough, it's up to you. My opinion is that I think two spacers only for the support are a bit light.
4. Also, on some of my spacers, I had the impression that they weren't perfectly orthogonal to the plane of their thread, is this the case for yours?


>3.If possible, please check the other assembly details for me and ask questions, I hope this won't waste too much of your time!

The only thing I can see are the M5 (half?) nuts you use. Personally, I designed HEMY with square T-nuts for 2020 profiles, diameter M5. For example: https://fr.aliexpress.com/item/32964780472.html

>4.Regarding those brakes, what are my options for testing and controlling them at this stage?

As long as the electronics dedicated to HEMY are not in place, there is no easy way to manage the brakes. I played with the brake simply by sending 24V, but also with this small circuit (https://www.electronics-lab.com/project/pwm-solenoid-and-valve-driver-using-drv103/). I think it's worth waiting for the electronics dedicated to HEMY, in the meantime, the brake isn't necessary as long as the setup isn't too heavy and there aren't any power cuts. For the two HEMYs I've built, the brake isn't installed inside.


Please don't hesitate to ask other questions, even if I'm a bit slow to answer (family life, etc :D ...)

**Comment by polvinc** [comment]
@martin0359 Were you able to solve any small problems you had during assembly?
