### ISSUE TITLE
Harmonic drive ratio

### ISSUE THREAD

**Issue by Trigger-broom-289** [polvinc/HEMY#9]
Hello,

I currently have a couple of 17-30 instead of the 17-100, would that work or do I have to get the 17-100 ratio model?

thanks

**Comment by polvinc** [comment]
I advise you to find out about reduction ratios, in relation to the angular resolution of the mount. In your case, a reduction ratio of 1:30 in the main with 1:5 in the pulley (for RA, 1:3.75 for DEC) is a bit tight in terms of real resolution. It will work, but you will have between 1 and 1.5 arcsec of resolution, which is a bit tight for astrophotography with long focal lengths.

<img width="1418" alt="Capture d’écran 2024-12-23 à 20 23 30" src="https://github.com/user-attachments/assets/6c824561-cbcc-4d34-8978-295ff41d3393" />

**Comment by Trigger-broom-289** [comment]
Thanks, I'll see if I order some new harmonic drives.
